# fly.toml app configuration file generated for treats-portfolio-cms on 2023-06-09T12:28:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "treats-portfolio-cms"
primary_region = "iad"

[[mounts]]
  source = "data"
  destination = "/app/public/uploads"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
